---
name: XHTML-Instrumented
version: 0.04
author:
  - '"G. Allen Morris III" <gam3@gam3.net>'
abstract: packages to control XHTML
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Params::Validate: 0
  XML::Parser: 0
  perl: 5.6.0
build_requires:
  Test::Warn: 0
  Test::XML: 0
recommends:
  Test::Pod: 0
  Test::XML::Order: 0.03
provides:
  XHTML::Instrumented:
    file: lib/XHTML/Instrumented.pm
    version: 0.04
  XHTML::Instrumented::Form:
    file: lib/XHTML/Instrumented/Form.pm
    version: 0.04
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
